CREATE TABLE IF NOT EXISTS "clients" (
    "ID" BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "NAME" VARCHAR(150) NOT NULL,
    "DNI" VARCHAR(20) NOT NULL UNIQUE,
    "GENDER" VARCHAR(10),
    "AGE" INTEGER CHECK (AGE >= 0),
    "ADDRESS" VARCHAR(255),
    "PHONE" VARCHAR(20),
    "PASSWORD" VARCHAR(255) NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE
);