/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.22.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.backend.api;

import com.backend.model.ClientDto;
import com.backend.model.PartialClientDto;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;
import org.springframework.http.codec.multipart.Part;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-05-02T21:48:26.382430100-05:00[America/Guayaquil]", comments = "Generator version: 7.22.0")
@Validated
@Tag(name = "api", description = "the api API")
public interface ApiApi {

    String PATH_CREATE_CLIENT = "/api/v1/customers";
    /**
     * POST /api/v1/customers : Crear cliente
     *
     * @param clientDto  (required)
     * @return Cliente creado (status code 201)
     *         or DNI ya existe (status code 409)
     */
    @Operation(
        operationId = "createClient",
        summary = "Crear cliente",
        responses = {
            @ApiResponse(responseCode = "201", description = "Cliente creado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDto.class))
            }),
            @ApiResponse(responseCode = "409", description = "DNI ya existe")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = ApiApi.PATH_CREATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<ClientDto>> createClient(
        @Parameter(name = "ClientDto", description = "", required = true) @Valid @RequestBody Mono<ClientDto> clientDto,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(clientDto).then(Mono.empty());

    }


    String PATH_DELETE_CLIENT = "/api/v1/customers/{id}";
    /**
     * DELETE /api/v1/customers/{id} : Eliminar cliente
     *
     * @param id  (required)
     * @return Eliminado correctamente (status code 204)
     *         or Cliente no encontrado (status code 404)
     */
    @Operation(
        operationId = "deleteClient",
        summary = "Eliminar cliente",
        responses = {
            @ApiResponse(responseCode = "204", description = "Eliminado correctamente"),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = ApiApi.PATH_DELETE_CLIENT
    )
    default Mono<ResponseEntity<Void>> deleteClient(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    

        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);

        return result.then(Mono.empty());

    }


    String PATH_GET_ALL_CLIENTS = "/api/v1/customers";
    /**
     * GET /api/v1/customers : Obtener todos los clientes
     *
     * @return Lista de clientes (status code 200)
     */
    @Operation(
        operationId = "getAllClients",
        summary = "Obtener todos los clientes",
        responses = {
            @ApiResponse(responseCode = "200", description = "Lista de clientes", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ClientDto.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_GET_ALL_CLIENTS,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<Flux<ClientDto>>> getAllClients(
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "[ { \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 }, { \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 } ]";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(Mono.empty());

    }


    String PATH_GET_CLIENT_BY_ID = "/api/v1/customers/{id}";
    /**
     * GET /api/v1/customers/{id} : Obtener cliente por ID
     *
     * @param id  (required)
     * @return Cliente encontrado (status code 200)
     *         or Cliente no encontrado (status code 404)
     */
    @Operation(
        operationId = "getClientById",
        summary = "Obtener cliente por ID",
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente encontrado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = ApiApi.PATH_GET_CLIENT_BY_ID,
        produces = { "application/json" }
    )
    default Mono<ResponseEntity<ClientDto>> getClientById(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(Mono.empty());

    }


    String PATH_PARTIAL_UPDATE_CLIENT = "/api/v1/customers/{id}";
    /**
     * PATCH /api/v1/customers/{id} : Actualización parcial (activar/desactivar)
     *
     * @param id  (required)
     * @param partialClientDto  (required)
     * @return Cliente actualizado parcialmente (status code 200)
     *         or Cliente no encontrado (status code 404)
     */
    @Operation(
        operationId = "partialUpdateClient",
        summary = "Actualización parcial (activar/desactivar)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado parcialmente", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDto.class))
            }),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.PATCH,
        value = ApiApi.PATH_PARTIAL_UPDATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<ClientDto>> partialUpdateClient(
        @Parameter(name = "id", description = "", required = true, in = ParameterIn.PATH) @PathVariable("id") Long id,
        @Parameter(name = "PartialClientDto", description = "", required = true) @Valid @RequestBody Mono<PartialClientDto> partialClientDto,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(partialClientDto).then(Mono.empty());

    }


    String PATH_UPDATE_CLIENT = "/api/v1/customers";
    /**
     * PUT /api/v1/customers : Actualizar cliente completo
     *
     * @param clientDto  (required)
     * @return Cliente actualizado (status code 200)
     *         or ID requerido (status code 400)
     *         or Cliente no encontrado (status code 404)
     */
    @Operation(
        operationId = "updateClient",
        summary = "Actualizar cliente completo",
        responses = {
            @ApiResponse(responseCode = "200", description = "Cliente actualizado", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = ClientDto.class))
            }),
            @ApiResponse(responseCode = "400", description = "ID requerido"),
            @ApiResponse(responseCode = "404", description = "Cliente no encontrado")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = ApiApi.PATH_UPDATE_CLIENT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default Mono<ResponseEntity<ClientDto>> updateClient(
        @Parameter(name = "ClientDto", description = "", required = true) @Valid @RequestBody Mono<ClientDto> clientDto,
        @Parameter(hidden = true) final ServerWebExchange exchange
    ) {
        Mono<Void> result = Mono.empty();
    
        exchange.getResponse().setStatusCode(HttpStatus.NOT_IMPLEMENTED);
        for (MediaType mediaType : exchange.getRequest().getHeaders().getAccept()) {
            if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                String exampleString = "{ \"password\" : \"password\", \"address\" : \"address\", \"gender\" : \"gender\", \"phone\" : \"phone\", \"name\" : \"name\", \"id\" : 0, \"isActive\" : true, \"dni\" : \"dni\", \"age\" : 6 }";
                result = ApiUtil.getExampleResponse(exchange, MediaType.valueOf("application/json"), exampleString);
                break;
            }
        }
    

        return result.then(clientDto).then(Mono.empty());

    }

}
